norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained=None,
    backbone=dict(
        type='BEiTAdapter',
        pretrain_size=224,
        conv_inplane=64,
        num_points=4,
        deform_num_heads=16,
        init_values=1e-6,
        cffn_ratio=0.25,
        cffn_drop_rate=0.,
        deform_ratio=0.5,
        with_cffn=True,
        interaction_indexes=[[0, 5], [6, 11], [12, 17], [18, 23]],
        add_vit_feature=True,
        use_extra_extractor=True,
        with_cp=False,
        img_size=640,
        patch_size=16,
        in_channels=3,
        embed_dims=1024,
        depth=24,
        num_heads=16,
        mlp_ratio=4,
        out_indices=-1,
        qv_bias=True,
        attn_drop_rate=0.,
        drop_path_rate=0.3,
        norm_cfg=dict(type='LN'),
        act_cfg=dict(type='GELU'),
        patch_norm=False,
        final_norm=False,
        num_fcs=2,
        norm_eval=False,
        init_cfg=None,
    ),
    decode_head=dict(
        type='UPerHead',
        in_channels=[1024, 1024, 1024, 1024],
        in_index=[0, 1, 2, 3],
        pool_scales=(1, 2, 3, 6),
        num_classes=150,
        channels=1024,
        dropout_ratio=0.1,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=1024,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=150,
        norm_cfg=norm_cfg,
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4)),
    # model training and testing settings
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
